"""fix_ticket_seller_fk

Revision ID: 0e6082cf7868
Revises: 74883545c149
Create Date: 2026-02-04 15:57:56.626205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '0e6082cf7868'
down_revision = '74883545c149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    foreign_keys = inspector.get_foreign_keys('ticket')
    for fk in foreign_keys:
        if fk.get('constrained_columns') == ['seller_id'] and fk.get('referred_table') == 'seller':
            name = fk.get('name')
            if name:
                with op.batch_alter_table('ticket', schema=None) as batch_op:
                    batch_op.drop_constraint(name, type_='foreignkey')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ticket_seller_id_user', 'user', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    foreign_keys = inspector.get_foreign_keys('ticket')
    for fk in foreign_keys:
        if fk.get('constrained_columns') == ['seller_id'] and fk.get('referred_table') == 'user':
            name = fk.get('name')
            if name:
                with op.batch_alter_table('ticket', schema=None) as batch_op:
                    batch_op.drop_constraint(name, type_='foreignkey')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ticket_seller_id_seller', 'seller', ['seller_id'], ['id'])

    # ### end Alembic commands ###
